export enum ProductActionType {
  GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS",
  GET_SELECTED_PRODUCTS = "GET_SELECTED_PRODUCTS",
  GET_AVAILABLE_PRODUCTS = "GET_AVAILABLE_PRODUCTS",
  NEW_PRODUCT = "NEW_PRODUCT",
  SEARCH_PRODUCT = "SEARCH_PRODUCT",
  SELECT_PRODUCT = "SELECT_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  EDIT_PRODUCT = "EDIT_PRODUCT",
}

export interface ActionEvent{
   type: ProductActionType,
   payload?: any
}
